[package]
name = "neptis-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_repr = "0.1.19"
serde_json = "1.0.139"
serde_with = "3.12.0"
url = "2.5.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
uuid = { version = "1.13.2", features = ["v4", "serde"] }
base64 = "0.22.1"
hmac = "0.12.1"
sha2 = "0.10.8"
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
aes = "0.8.4"
cbc = { version = "0.1.2", features = ["alloc"] }
totp-rs = { version = "5.6.0", features = ["gen_secret", "serde_support"] }
thiserror = "2.0.12"
chrono = "0.4.39"