[package]
name = "neptis-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_repr = "0.1.19"
serde_json = "1.0.139"
serde_with = "3.12.0"
url = "2.5.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
uuid = { version = "1.13.2", features = ["v4", "serde"] }
derive_more = { version = "2.0.1", features = ["full"]}
base64 = "0.22.1"
hmac = "0.12.1"
sha2 = "0.10.8"
rand = "0.9.0"
aes-gcm = "0.10.3"
http = "1.2.0"