[workspace]
members = ["cargo:."]



# [workspace.metadata.dist.dependencies.apt]
# fuse = "*"
# fuse3 = "*"
# libfuse3-dev = "*"
# libfuse-dev = "*"
# pkg-config = "*"


# [workspace.metadata.dist.dependencies.homebrew]
# macfuse = "*"
# osxfuse = "*"
# fuse = "*"
# pkg-config = "*"


# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.5"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
github-build-setup = "build-setup.yml"

# [dependencies.homebrew]
# macfuse = "*"
# osxfuse = "*"
# fuse = "*"
# pkg-config = "*"

# [dependencies.apt]
# fuse = "*"
# fuse3 = "*"
# libfuse3-dev = "*"
# libfuse-dev = "*"
# pkg-config = "*"

# [dist.github-custom-runners]
# x86_64-unknown-linux-gnu = "ubuntu-latest"
# x86_64-pc-windows-msvc = "windows-latest"
