/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::configuration::ApiBuilder;
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// struct for typed errors of method [`authenticate`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthenticateError {
    UnknownValue(serde_json::Value),
}

pub async fn authenticate(
    configuration: &configuration::Configuration,
    auth_input_dto: Option<models::AuthInputDto>,
) -> Result<models::AuthOutputDto, Error<AuthenticateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_auth_input_dto = auth_input_dto;
    let uri_str = format!("{}/api/auth", configuration.base_path);
    ApiBuilder::new(configuration, reqwest::Method::POST, &uri_str)
        .with_body(p_auth_input_dto)
        .execute()
        .await
}
