/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobBackupDto {
    #[serde(
        rename = "path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path: Option<Option<String>>,
    #[serde(rename = "repoPoint", skip_serializing_if = "Option::is_none")]
    pub repo_point: Option<Box<models::BasePointIdentifyDto>>,
}

impl JobBackupDto {
    pub fn new() -> JobBackupDto {
        JobBackupDto {
            path: None,
            repo_point: None,
        }
    }
}
