/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoJobGetDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "dataPoint", skip_serializing_if = "Option::is_none")]
    pub data_point: Option<Box<models::BasePointIdentifyDto>>,
    #[serde(rename = "repoPoint", skip_serializing_if = "Option::is_none")]
    pub repo_point: Option<Box<models::BasePointIdentifyDto>>,
}

impl AutoJobGetDto {
    pub fn new(name: String) -> AutoJobGetDto {
        AutoJobGetDto {
            name,
            data_point: None,
            repo_point: None,
        }
    }
}

