/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoJobPutDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "dataPoint", skip_serializing_if = "Option::is_none")]
    pub data_point: Option<Box<models::BasePointIdentifyDto>>,
    #[serde(rename = "repoPoint", skip_serializing_if = "Option::is_none")]
    pub repo_point: Option<Box<models::BasePointIdentifyDto>>,
    #[serde(rename = "schedule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Option<String>>,
    #[serde(rename = "newName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<Option<String>>,
    #[serde(rename = "backupPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub backup_path: Option<Option<String>>,
}

impl AutoJobPutDto {
    pub fn new(name: String) -> AutoJobPutDto {
        AutoJobPutDto {
            name,
            data_point: None,
            repo_point: None,
            schedule: None,
            new_name: None,
            backup_path: None,
        }
    }
}

