/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasePointIdentifyDto {
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "pointName")]
    pub point_name: String,
}

impl BasePointIdentifyDto {
    pub fn new(user_name: String, point_name: String) -> BasePointIdentifyDto {
        BasePointIdentifyDto {
            user_name,
            point_name,
        }
    }
}
