/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CpuItemDto {
    #[serde(
        rename = "cpu",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cpu: Option<Option<String>>,
    #[serde(rename = "userPercent", skip_serializing_if = "Option::is_none")]
    pub user_percent: Option<f64>,
    #[serde(rename = "nicePercent", skip_serializing_if = "Option::is_none")]
    pub nice_percent: Option<f64>,
    #[serde(rename = "systemPercent", skip_serializing_if = "Option::is_none")]
    pub system_percent: Option<f64>,
    #[serde(rename = "ioWaitPercent", skip_serializing_if = "Option::is_none")]
    pub io_wait_percent: Option<f64>,
    #[serde(rename = "irqPercent", skip_serializing_if = "Option::is_none")]
    pub irq_percent: Option<f64>,
    #[serde(rename = "softPercent", skip_serializing_if = "Option::is_none")]
    pub soft_percent: Option<f64>,
    #[serde(rename = "stealPercent", skip_serializing_if = "Option::is_none")]
    pub steal_percent: Option<f64>,
    #[serde(rename = "guestPercent", skip_serializing_if = "Option::is_none")]
    pub guest_percent: Option<f64>,
    #[serde(rename = "idlePercent", skip_serializing_if = "Option::is_none")]
    pub idle_percent: Option<f64>,
    #[serde(rename = "usedPercent", skip_serializing_if = "Option::is_none")]
    pub used_percent: Option<f64>,
}

impl CpuItemDto {
    pub fn new() -> CpuItemDto {
        CpuItemDto {
            cpu: None,
            user_percent: None,
            nice_percent: None,
            system_percent: None,
            io_wait_percent: None,
            irq_percent: None,
            soft_percent: None,
            steal_percent: None,
            guest_percent: None,
            idle_percent: None,
            used_percent: None,
        }
    }
}
