/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataPointBrowseGetDto {
    #[serde(
        rename = "path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path: Option<Option<String>>,
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
}

impl DataPointBrowseGetDto {
    pub fn new() -> DataPointBrowseGetDto {
        DataPointBrowseGetDto {
            path: None,
            depth: None,
        }
    }
}
