/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataPointShareDto {
    #[serde(
        rename = "userName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
    #[serde(rename = "canRead", skip_serializing_if = "Option::is_none")]
    pub can_read: Option<bool>,
    #[serde(rename = "canWrite", skip_serializing_if = "Option::is_none")]
    pub can_write: Option<bool>,
    #[serde(rename = "canShare", skip_serializing_if = "Option::is_none")]
    pub can_share: Option<bool>,
    #[serde(rename = "canManage", skip_serializing_if = "Option::is_none")]
    pub can_manage: Option<bool>,
}

impl DataPointShareDto {
    pub fn new() -> DataPointShareDto {
        DataPointShareDto {
            user_name: None,
            can_read: None,
            can_write: None,
            can_share: None,
            can_manage: None,
        }
    }
}
