/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepoDataJobStatusDto {
    #[serde(rename = "jobId", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<uuid::Uuid>,
    #[serde(rename = "secondsElapsed", skip_serializing_if = "Option::is_none")]
    pub seconds_elapsed: Option<i32>,
    #[serde(rename = "secondsRemaining", skip_serializing_if = "Option::is_none")]
    pub seconds_remaining: Option<i32>,
    #[serde(rename = "percentDone", skip_serializing_if = "Option::is_none")]
    pub percent_done: Option<f64>,
    #[serde(rename = "totalFiles", skip_serializing_if = "Option::is_none")]
    pub total_files: Option<i32>,
    #[serde(rename = "filesDone", skip_serializing_if = "Option::is_none")]
    pub files_done: Option<i32>,
    #[serde(rename = "totalBytes", skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<i64>,
    #[serde(rename = "bytesDone", skip_serializing_if = "Option::is_none")]
    pub bytes_done: Option<i64>,
    #[serde(rename = "errorCount", skip_serializing_if = "Option::is_none")]
    pub error_count: Option<i32>,
    #[serde(rename = "currentFiles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_files: Option<Option<Vec<String>>>,
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl RepoDataJobStatusDto {
    pub fn new() -> RepoDataJobStatusDto {
        RepoDataJobStatusDto {
            job_id: None,
            seconds_elapsed: None,
            seconds_remaining: None,
            percent_done: None,
            total_files: None,
            files_done: None,
            total_bytes: None,
            bytes_done: None,
            error_count: None,
            current_files: None,
            last_updated: None,
        }
    }
}

