/*
 * Neptis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WsConfigItemDto {
    #[serde(
        rename = "userName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
    #[serde(
        rename = "uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub uri: Option<Option<String>>,
    #[serde(
        rename = "method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub method: Option<Option<String>>,
    #[serde(
        rename = "subscriptions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscriptions: Option<Option<Vec<String>>>,
}

impl WsConfigItemDto {
    pub fn new() -> WsConfigItemDto {
        WsConfigItemDto {
            user_name: None,
            uri: None,
            method: None,
            subscriptions: None,
        }
    }
}
